/* tslint:disable */
/* eslint-disable */
/**
 * Engraving4All API
 * API for Engraving4All, pulling data from multiple services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ApiDatabaseHealthGet200Response
 */
export interface ApiDatabaseHealthGet200Response {
    /**
     * Status message
     * @type {string}
     * @memberof ApiDatabaseHealthGet200Response
     */
    'status'?: string;
}
/**
 * 
 * @export
 * @interface ApiDatabaseHealthGet500Response
 */
export interface ApiDatabaseHealthGet500Response {
    /**
     * Status message
     * @type {string}
     * @memberof ApiDatabaseHealthGet500Response
     */
    'status'?: string;
}
/**
 * 
 * @export
 * @interface ApiDatabaseImagesGet500Response
 */
export interface ApiDatabaseImagesGet500Response {
    /**
     * Status message
     * @type {string}
     * @memberof ApiDatabaseImagesGet500Response
     */
    'status'?: string;
}
/**
 * 
 * @export
 * @interface ApiDatabaseProductsGet500Response
 */
export interface ApiDatabaseProductsGet500Response {
    /**
     * Error message
     * @type {string}
     * @memberof ApiDatabaseProductsGet500Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * The ID of the image
     * @type {number}
     * @memberof Image
     */
    'id'?: number;
    /**
     * The URL of the image
     * @type {string}
     * @memberof Image
     */
    'url'?: string;
    /**
     * The alt text for the image
     * @type {string}
     * @memberof Image
     */
    'alt_text'?: string;
}
/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * The ID of the product
     * @type {number}
     * @memberof Product
     */
    'id'?: number;
}
/**
 * 
 * @export
 * @interface Testimonial
 */
export interface Testimonial {
    /**
     * The ID of the testimonial
     * @type {number}
     * @memberof Testimonial
     */
    'id'?: number;
    /**
     * The logo URL of the client
     * @type {string}
     * @memberof Testimonial
     */
    'logo'?: string;
    /**
     * The name of the client
     * @type {string}
     * @memberof Testimonial
     */
    'name'?: string;
    /**
     * The testimonial content
     * @type {string}
     * @memberof Testimonial
     */
    'description'?: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Performs a simple query to verify that the database connection is operational
         * @summary Check database health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDatabaseHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/database/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch all image records from the database
         * @summary Get all images
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDatabaseImagesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/database/images`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch all products from the database
         * @summary Get all products
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDatabaseProductsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/database/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch all testimonials that are set to showcase and order them by the \"order\" column
         * @summary Get all testimonials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDatabaseTestimonialsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/database/testimonials`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Performs a simple query to verify that the database connection is operational
         * @summary Check database health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDatabaseHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiDatabaseHealthGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDatabaseHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiDatabaseHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetch all image records from the database
         * @summary Get all images
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDatabaseImagesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Image>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDatabaseImagesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiDatabaseImagesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetch all products from the database
         * @summary Get all products
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDatabaseProductsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Product>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDatabaseProductsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiDatabaseProductsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetch all testimonials that are set to showcase and order them by the \"order\" column
         * @summary Get all testimonials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDatabaseTestimonialsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Testimonial>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDatabaseTestimonialsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiDatabaseTestimonialsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Performs a simple query to verify that the database connection is operational
         * @summary Check database health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDatabaseHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<ApiDatabaseHealthGet200Response> {
            return localVarFp.apiDatabaseHealthGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch all image records from the database
         * @summary Get all images
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDatabaseImagesGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<Image>> {
            return localVarFp.apiDatabaseImagesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch all products from the database
         * @summary Get all products
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDatabaseProductsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<Product>> {
            return localVarFp.apiDatabaseProductsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch all testimonials that are set to showcase and order them by the \"order\" column
         * @summary Get all testimonials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDatabaseTestimonialsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<Testimonial>> {
            return localVarFp.apiDatabaseTestimonialsGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Performs a simple query to verify that the database connection is operational
     * @summary Check database health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiDatabaseHealthGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiDatabaseHealthGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetch all image records from the database
     * @summary Get all images
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiDatabaseImagesGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiDatabaseImagesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetch all products from the database
     * @summary Get all products
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiDatabaseProductsGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiDatabaseProductsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetch all testimonials that are set to showcase and order them by the \"order\" column
     * @summary Get all testimonials
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiDatabaseTestimonialsGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiDatabaseTestimonialsGet(options).then((request) => request(this.axios, this.basePath));
    }
}



